## Docker-Compose file is used to start dependent services

version: '3'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: flowci-debug-db
    ports:
      - "27017:27017"

  zk:
    image: zookeeper:3.4
    container_name: flowci-debug-zk
    restart: always
    ports:
      - "2181:2181"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-debug-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: flowci-debug-minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
    command: server /data